In [ ]:
from google.colab import drive
drive.mount('/content/drive/') 
# click on the url that pops up and give the necessary authorizations

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
cd drive/MyDrive

/content/drive/MyDrive

In [ ]:
# Load the Pandas libraries with alias 'pd' 
import pandas as pd 
from tensorflow import keras
import matplotlib.pyplot as plt
import random
import numpy as np
from collections import Counter
import operator

df_train = pd.read_excel("updated_train.xlsx")
df_test = pd.read_excel("processedtest.xlsx")


df_train.head()

df_test

       Unnamed: 0     ID   brand          model  ...   mpg engineSize  tax tax(Â£)
0               0      0    ford           Edge  ...  48.7        2.0  145      0
1               1      1    merc      CLA Class  ...  44.8        1.3  145      0
2               2      2     bmw       1 Series  ...  56.5        1.5  150      0
3               3      3    audi             Q3  ...  50.4        2.0  145      0
4               4      4      vw           Golf  ...  39.8        2.0  200      0
...           ...    ...     ...            ...  ...   ...        ...  ...    ...
25550       25550  25550  toyota   Land Cruiser  ...  30.1        2.8  145      0
25551       25551  25551    merc      GLC Class  ...  40.4        2.0  145      0
25552       25552  25552  toyota        Corolla  ...  53.3        2.0  135      0
25553       25553  25553  toyota          Yaris  ...  55.0        1.3   30      0
25554       25554  25554     bmw       3 Series  ...  47.9        2.0  145      0

[25555 rows x 12 columns]

In [ ]:
df_train.columns

Index(['Unnamed: 0', 'ID', 'brand', 'model', 'year', 'transmission', 'mileage',
       'fuelType', 'mpg', 'engineSize', 'tax', 'tax(Â£)', 'price'],
      dtype='object')

In [ ]:
df_train.drop("Unnamed: 0", axis=1, inplace=True)
df_train.head() 

df_test.drop("Unnamed: 0", axis=1, inplace=True)
df_test.head()

   ID brand       model  year  ...   mpg  engineSize  tax  tax(Â£)
0   0  ford        Edge  2017  ...  48.7         2.0  145       0
1   1  merc   CLA Class  2020  ...  44.8         1.3  145       0
2   2   bmw    1 Series  2017  ...  56.5         1.5  150       0
3   3  audi          Q3  2017  ...  50.4         2.0  145       0
4   4    vw        Golf  2016  ...  39.8         2.0  200       0

[5 rows x 11 columns]

In [ ]:
df_train.set_index('ID',inplace=True)
df_train.head()

df_test.set_index('ID',inplace=True)
df_test.head()

   brand       model  year transmission  ...   mpg engineSize  tax  tax(Â£)
ID                                       ...
0   ford        Edge  2017       Manual  ...  48.7        2.0  145       0
1   merc   CLA Class  2020    Automatic  ...  44.8        1.3  145       0
2    bmw    1 Series  2017       Manual  ...  56.5        1.5  150       0
3   audi          Q3  2017       Manual  ...  50.4        2.0  145       0
4     vw        Golf  2016       Manual  ...  39.8        2.0  200       0

[5 rows x 10 columns]

In [ ]:
df_train.describe()

               year        mileage  ...        tax(Â£)          price
count  59999.000000   59999.000000  ...  59999.000000   59999.000000
mean    2017.110719   23003.825080  ...      6.816030   17842.607527
std        2.117563   21290.447163  ...     31.185833   10206.145921
min     1970.000000       2.000000  ...      0.000000     495.000000
25%     2016.000000    7045.500000  ...      0.000000   10795.000000
50%     2017.000000   17212.000000  ...      0.000000   15750.000000
75%     2019.000000   32449.000000  ...      0.000000   21998.000000
max     2020.000000  323003.000000  ...    555.000000  159999.000000

[8 rows x 7 columns]

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59999 entries, 0 to 59999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         59999 non-null  object
 1   model         59999 non-null  object
 2   year          59999 non-null  int64
 3   transmission  59999 non-null  object
 4   mileage       59999 non-null  int64
 5   fuelType      59999 non-null  object
 6   mpg           59999 non-null  float64
 7   engineSize    59999 non-null  float64
 8   tax           59999 non-null  int64
 9   tax(Â£)        59999 non-null  int64
 10  price         59999 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 5.5+ MB

In [ ]:
from matplotlib import pyplot
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error as MSE
from xgboost import plot_importance
from matplotlib import pyplot


#Auto-Sklearn
!pip install --upgrade scipy
!pip install auto-sklearn


import autosklearn.regression
from sklearn.metrics import mean_absolute_error
from autosklearn.regression import AutoSklearnRegressor
from autosklearn.metrics import mean_absolute_error as auto_mean_absolute_error

#TPOT
!pip install tpot
from sklearn.model_selection import RepeatedKFold
from tpot import TPOTRegressor


#RFT

from sklearn.ensemble import RandomForestRegressor

Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (1.7.3)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /usr/local/lib/python3.7/dist-packages (from scipy) (1.19.5)
Requirement already satisfied: auto-sklearn in /usr/local/lib/python3.7/dist-packages (0.14.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (57.4.0)
Requirement already satisfied: smac>=0.14 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.1.1)
Requirement already satisfied: dask<2021.07 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (2021.6.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (3.13)
Requirement already satisfied: pyrfr<0.9,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (0.8.2)
Requirement already satisfied: scikit-learn<0.25.0,>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (0.24.2)
Requirement already satisfied: threadpoolctl in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (3.0.0)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.1.5)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (3.10.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.7.3)
Requirement already satisfied: distributed<2021.07,>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (2021.6.2)
Requirement already satisfied: liac-arff in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (2.5.0)
Requirement already satisfied: pynisher>=0.6.3 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (0.6.4)
Requirement already satisfied: ConfigSpace<0.5,>=0.4.14 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (0.4.20)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.19.5)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.1.0)
Requirement already satisfied: cython in /usr/local/lib/python3.7/dist-packages (from ConfigSpace<0.5,>=0.4.14->auto-sklearn) (0.29.24)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.7/dist-packages (from ConfigSpace<0.5,>=0.4.14->auto-sklearn) (3.0.6)
Requirement already satisfied: partd>=0.3.10 in /usr/local/lib/python3.7/dist-packages (from dask<2021.07->auto-sklearn) (1.2.0)
Requirement already satisfied: toolz>=0.8.2 in /usr/local/lib/python3.7/dist-packages (from dask<2021.07->auto-sklearn) (0.11.2)
Requirement already satisfied: fsspec>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from dask<2021.07->auto-sklearn) (2021.11.1)
Requirement already satisfied: cloudpickle>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from dask<2021.07->auto-sklearn) (2.0.0)
Requirement already satisfied: zict>=0.1.3 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (2.0.0)
Requirement already satisfied: msgpack>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (1.0.3)
Requirement already satisfied: psutil>=5.0 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (5.4.8)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (1.7.0)
Requirement already satisfied: tornado>=5 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (5.1.1)
Requirement already satisfied: click>=6.6 in /usr/local/lib/python3.7/dist-packages (from distributed<2021.07,>=2.2.0->auto-sklearn) (7.1.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0->auto-sklearn) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0->auto-sklearn) (2018.9)
Requirement already satisfied: locket in /usr/local/lib/python3.7/dist-packages (from partd>=0.3.10->dask<2021.07->auto-sklearn) (0.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.0->auto-sklearn) (1.15.0)
Requirement already satisfied: emcee>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from smac>=0.14->auto-sklearn) (3.1.1)
Requirement already satisfied: heapdict in /usr/local/lib/python3.7/dist-packages (from zict>=0.1.3->distributed<2021.07,>=2.2.0->auto-sklearn) (1.0.1)
Collecting tpot
  Downloading TPOT-0.11.7-py3-none-any.whl (87 kB)
     |ââââââââââââââââââââââââââââââââ| 87 kB 3.0 MB/s
Collecting deap>=1.2
  Downloading deap-1.3.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (160 kB)
     |ââââââââââââââââââââââââââââââââ| 160 kB 24.9 MB/s
Collecting update-checker>=0.16
  Downloading update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.7/dist-packages (from tpot) (1.7.3)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from tpot) (1.1.5)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.7/dist-packages (from tpot) (4.62.3)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.7/dist-packages (from tpot) (0.24.2)
Collecting stopit>=1.1.1
  Downloading stopit-1.1.2.tar.gz (18 kB)
Requirement already satisfied: numpy>=1.16.3 in /usr/local/lib/python3.7/dist-packages (from tpot) (1.19.5)
Collecting xgboost>=1.1.0
  Downloading xgboost-1.5.1-py3-none-manylinux2014_x86_64.whl (173.5 MB)
     |ââââââââââââââââââââââââââââââââ| 173.5 MB 13 kB/s
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.7/dist-packages (from tpot) (1.1.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->tpot) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->tpot) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.2->tpot) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.22.0->tpot) (3.0.0)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from update-checker>=0.16->tpot) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->update-checker>=0.16->tpot) (3.0.4)
Building wheels for collected packages: stopit
  Building wheel for stopit (setup.py) ... done
  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11952 sha256=a20fdd4d767b8821e7c8ec3a051617bfcc9246304db4aab133b55689a24432f2
  Stored in directory: /root/.cache/pip/wheels/e2/d2/79/eaf81edb391e27c87f51b8ef901ecc85a5363dc96b8b8d71e3
Successfully built stopit
Installing collected packages: xgboost, update-checker, stopit, deap, tpot
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90
Successfully installed deap-1.3.1 stopit-1.1.2 tpot-0.11.7 update-checker-0.18.0 xgboost-1.5.1

In [ ]:
#!pip install tpot
from sklearn.linear_model import ElasticNetCV
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline, make_union
from sklearn.tree import DecisionTreeRegressor
from tpot.builtins import StackingEstimator
from tpot.export_utils import set_param_recursive

from xgboost import plot_tree
from sklearn.model_selection import GridSearchCV

In [ ]:
#Encoding Options (Ref: https://songxia-sophia.medium.com/two-machine-learning-algorithms-to-predict-xgboost-neural-network-with-entity-embedding-caac68717dea)
'''
1. Target encoding: each level of categorical variable is represented by a summary statistic of the target for that level.

2. One-hot encoding: assign 1 to specific category and 0 to other category and transform categorical variable to dummy variable.

3. Label encoding: assign ordinal integer to different categorical levels of categorical variable.

4. Entity embedding: map categorical variables in a function approximation problem into Euclidean spaces, 
and mapping similar values close to each other in the embedding space, and it reveals the intrinsic properties of the categorical variables. 
Usually the mapping is trained by a neural network during the standard supervised training 
process, it not only reduces memory usage and speeds up computational efficiency compared with one-hot encoding. 

'''

In [ ]:
#Grid Serach 

param={'n_estimators':[2000],
 'max_depth':range(4,10),
 'eta':[0.5]}

In [ ]:
# define Target & Features & Run Model
def run_model(df,df_test,encode_name,v1,v2,model):
  y = df['price']
  X = df.loc[:,df.columns!='price']


  # Split Train - Test Datasets
  X_train, X_test, y_train ,y_test = train_test_split(X,y,test_size=0.20,random_state=100)

  if model == "xgb":
    # Instantiation
    xgb_r = xgb.XGBRegressor( objective ='reg:linear',
                      n_estimators = 1300, seed = 123, learning_rate=0.50, max_depth=4, colsample_bytree = 1)

    #Hyper-parameter Tuning
    #gs=GridSearchCV(estimator=xgb_r,param_grid=param,scoring='r2',cv=5,verbose=3)
    #gs.fit(X_train,y_train)

    #print(gs.best_params_)
    #print(gs.best_score_)

    
    # Fitting the model
    xgb_r.fit(X_train, y_train)
      
    # Predict the model
    pred = xgb_r.predict(X_test)
      
    # RMSE Computation
    rmse = np.sqrt(MSE(y_test, pred))
    mae = mean_absolute_error(y_test, pred)
    print("Encode: ",encode_name,"| XGB RMSE : % f" %(rmse))
    print("Encode: ",encode_name,"| XGB MAE : % f" %(mae))
    print('R2Score: ',xgb_r.score(X_test,y_test))

    '''  
    ##Create the predicted value csv
    pred_final = pd.DataFrame(pred)

    print(pred_final)

    df_final = df_test.reset_index()

    df_final["price"] = pred_final.reset_index()[0]

    print(df_final)
    
    #df_final["ID"] = df_final[["id"]]

    df_final = df_final[['ID','price']]

    print(df_final.shape)

    df_final.to_csv("submission_tuned_last.csv",index=False)
    
    

    #Feature Importance
    fig,ax = pyplot.subplots(figsize=(v1,v2))
    plot_importance(xgb_r,ax=ax)
    pyplot.show()

    #XGB Decision Tree Visualization

    #fig,ax = pyplot.subplots(figsize=(v1,v2))
    #plot_tree(xgb_r,ax=ax)
    #plt.show()
    '''
    

  elif model == "automl": #https://machinelearningmastery.com/auto-sklearn-for-automated-machine-learning-in-python/
    # define search
    model = AutoSklearnRegressor(time_left_for_this_task=5*60, per_run_time_limit=30, n_jobs=8)
    # perform the search
    model.fit(X_train, y_train )
    # summarize
    print(model.sprint_statistics())
    # evaluate best model
    y_hat = model.predict(X_test)

    rmse = np.sqrt(MSE(y_test, y_hat))
    mae = mean_absolute_error(y_test, y_hat)

    print("Encode:",encode_name," |Auto ML MAE: %.3f" % mae)
    print("Encode:",encode_name," |Auto ML RMSE: %.3f" % rmse)
    print('R2Score: ',model.score(X_test,y_test))

  elif model == "tpot": #http://epistasislab.github.io/tpot/
    # define evaluation procedure
    cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
    # define search
    model = TPOTRegressor(generations=5, population_size=50, scoring='neg_mean_absolute_error', 
                        cv=cv, verbosity=2, random_state=1, n_jobs=-1)
    model.fit(X_train, y_train)
    # export the best model
    model.export('car_price_best_model.py')

    y_hat = model.predict(X_test)

    rmse = np.sqrt(MSE(y_test, y_hat))
    mae = mean_absolute_error(y_test, y_hat)
    print("Encode:",encode_name," |TPOT MAE: %.3f" % mae)
    print("Encode:",encode_name," |TPOT RMSE: %.3f" % rmse)

    


  elif model == "RFT":
    exported_pipeline = RandomForestRegressor(bootstrap=True, max_features=0.1, 
                                              min_samples_leaf=4, min_samples_split=16, n_estimators=100)
    exported_pipeline.fit(X_train, y_train)
    results = exported_pipeline.predict(X_test)

    rmse = np.sqrt(MSE(y_test, results))
    mae = mean_absolute_error(y_test, results)
    print("Encode:",encode_name," |Random Forest MAE: %.3f" % mae)
    print("Encode:",encode_name," |Random Forest RMSE: %.3f" % rmse)
    print('R2Score: ',exported_pipeline.score(X_test,y_test))


  elif model == "DT":
    # Average CV score on the training set was: -1698.8125906693422
    
    exported_pipeline = make_pipeline(
    StackingEstimator(estimator=DecisionTreeRegressor(max_depth=9, min_samples_leaf=5, min_samples_split=20)),
    StackingEstimator(estimator=ElasticNetCV(l1_ratio=0.8500000000000001, tol=0.001)),
    DecisionTreeRegressor(max_depth=8, min_samples_leaf=20, min_samples_split=11))

    # Fix random state for all the steps in exported pipeline
    set_param_recursive(exported_pipeline.steps, 'random_state', 1)

    exported_pipeline.fit(X_train, y_train)
    results = exported_pipeline.predict(X_test)

    rmse = np.sqrt(MSE(y_test, results))
    mae = mean_absolute_error(y_test, results)
    print("Encode:",encode_name," |TPOT DT MAE: %.3f" % mae)
    print("Encode:",encode_name," |TPOT DT Forest RMSE: %.3f" % rmse)
    print('R2Score: ',exported_pipeline.score(X_test,y_test))

In [ ]:
#Target Encoding

df_train1 = df_train

target_encode_columns = ['brand', 'model', 'transmission', 'fuelType']
target = ['price']
target_encode_df = df_train1[target_encode_columns + target].reset_index().drop(columns = 'ID', axis = 1)

target_name = target[0]
target_df = pd.DataFrame()

for embed_col in target_encode_columns:
    val_map = target_encode_df.groupby(embed_col)[target].mean().to_dict()[target_name]
    target_df[embed_col] = target_encode_df[embed_col].map(val_map).values
    
score_target_drop = df_train1.drop(target_encode_columns, axis = 1).reset_index().drop(columns = 'ID', axis = 1)
score_target = pd.concat([score_target_drop, target_df], axis = 1)




#print(score_target)

run_model(score_target,score_target,"Target Encoding",10,8,"xgb")
#run_model(score_target,"Target Encoding",10,8,"automl")
#run_model(score_target,"Target Encoding",10,8,"tpot")
#run_model(score_target,"Target Encoding",10,8,"RFT")
#run_model(score_target,score_target,"Target Encoding",10,8,"DT")

In [ ]:
#Label Encoding

df_train2 = df_train

encode_columns = ['brand', 'model', 'transmission', 'fuelType']


encode_df = df_train2[encode_columns]
encode_df = encode_df.astype('str')
encode_df = encode_df.apply(LabelEncoder().fit_transform)
score_encode_drop = df_train2.drop(encode_columns, axis = 1)
score_encode = pd.concat([score_encode_drop, encode_df], axis = 1)

df_test2 = df_test

encode_columns = ['brand', 'model', 'transmission', 'fuelType']


encode_df = df_test2[encode_columns]
encode_df = encode_df.astype('str')
encode_df = encode_df.apply(LabelEncoder().fit_transform)
score_encode_drop = df_test2.drop(encode_columns, axis = 1)
score_encode_test = pd.concat([score_encode_drop, encode_df], axis = 1)

#score_encode

run_model(score_encode,score_encode_test,"Label Encoding",30,30,"xgb")
#run_model(score_encode,"Label Encoding",10,8,"automl")
#run_model(score_encode,"Label Encoding",10,8,"tpot")
#run_model(score_encode,"Label Encoding",10,8,"RFT")
#run_model(score_target,score_target,"Label Encoding",10,8,"DT")
#tuning(score_encode)

[09:42:17] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
Encode:  Label Encoding | XGB RMSE :  2040.467970
Encode:  Label Encoding | XGB MAE :  1273.245738
R2Score:  0.9594993572920755

In [ ]:
#One-Hot Encoding

df_train3 = df_train
df_train3_test = df_test

onehot_columns = ['brand', 'model', 'transmission', 'fuelType']


onehot_df = df_train3[onehot_columns]
onehot_df = pd.get_dummies(onehot_df, columns = onehot_columns)
score_onehot_drop = df_train3.drop(onehot_columns, axis = 1)
score_onehot = pd.concat([score_onehot_drop, onehot_df], axis = 1)



onehot_df_test = df_train3_test[onehot_columns]
onehot_df_test = pd.get_dummies(onehot_df_test, columns = onehot_columns)
score_onehot_drop_test = df_train3_test.drop(onehot_columns, axis = 1)
score_onehot_test = pd.concat([score_onehot_drop_test, onehot_df_test], axis = 1)


train_cols = list(score_onehot.columns)
test_cols = list(score_onehot_test.columns)
cols_not_in_test = {c:0 for c in train_cols if c not in test_cols}
score_onehot_test = score_onehot_test.assign(**cols_not_in_test)

a = score_onehot.columns.intersection(score_onehot_test.columns)
score_onehot_test = score_onehot_test[a]

score_onehot_test.drop('price',inplace=True,axis=1)


print(score_onehot.shape)
print(score_onehot_test.shape)

#score_onehot

run_model(score_onehot,score_onehot_test,"One-Hot Encoding",30,35,"xgb")
#run_model(score_onehot,score_onehot_test,"One-Hot Encoding",10,8,"automl")
#run_model(score_encode,"One-Hot Encoding",10,8,"tpot")
#run_model(score_onehot,score_onehot_test,"One-Hot Encoding",20,25,"RFT")
#run_model(score_onehot,score_onehot_test,"One-Hot Encoding",20,25,"DT")
#tuning(score_onehot)

(59999, 194)
(25555, 193)
[10:59:33] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
Encode:  One-Hot Encoding | XGB RMSE :  1967.351074
Encode:  One-Hot Encoding | XGB MAE :  1210.267807
R2Score:  0.962349904279023

In [ ]:
### Hyper-Parameter Tuning XGB ### https://towardsdatascience.com/xgboost-fine-tune-and-optimize-your-model-23d996fab663

In [ ]:
from sklearn.model_selection import GridSearchCV

def tuning (df):

  y = df['price']
  X = df.loc[:,df.columns!='price']

  # Split Train - Test Datasets
  X_train, X_test, y_train ,y_test = train_test_split(X,y,test_size=0.2,random_state=100)

  params = { 'max_depth': [3,6,10],
            'learning_rate': [0.01, 0.05, 0.1],
            'n_estimators': [100, 500, 1000],
            'colsample_bytree': [0.3, 0.7]}

  xgbr = xgb.XGBRegressor(seed = 20)
  clf = GridSearchCV(estimator=xgbr, 
                    param_grid=params,
                    scoring='neg_mean_squared_error', 
                    verbose=3)
  clf.fit(X_train, y_train)
  print("Best parameters:", clf.best_params_)
  print("Lowest RMSE: ", (-clf.best_score_)**(1/2.0))